FROM php:8.2-fpm

# Définir le répertoire de travail
WORKDIR /var/www/html

# Copier les fichiers de www dans le conteneur
COPY ../www /var/www/html

# Autres instructions si nécessaire (par exemple, pour installer des extensions PHP)
